--- # Deploy

# Remove old rollbacks so they aren't used accidentally after errors.
- name: remove the old rollback
  file: dest={{ rollback_path }} state=absent
  tags: clone

- name: remove the old rollback database
  file: dest={{ rollback_sql_path }} state=absent
  tags: clone

#----------------
# Build codebase

- name: remove the old build path
  file: dest={{ build_path }} state=absent
  tags: clone

- name: build codebase from git repo at version
  git: repo={{ git_repo }} dest={{ build_path }} version="{{ version }}" force=yes
  tags: clone

# TODO: Ugly hack until we have better configuration management
- name: symlink into the repo
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes owner={{ user }}
  with_items:
    - { src: "{{ assets_path }}", dest: "{{ build_path }}/public/assets" }
    - { src: "{{ system_path }}", dest: "{{ build_path }}/public/system" }
    - { src: "{{ spree_path }}", dest: "{{ build_path }}/public/spree" }
    - { src: "{{ config_path }}/post-receive", dest: "{{ build_path }}/.git/hooks/post-receive" }
    - { src: "{{ config_path }}/database.yml", dest: "{{ build_path }}/config/database.yml" }
    - { src: "{{ config_path }}/seeds.rb", dest: "{{ build_path }}/db/seeds.rb" }
    - { src: "{{ config_path }}/states.yml", dest: "{{ build_path }}/db/default/spree/states.yml" }
    - { src: "{{ config_path }}/suburb_seeds.rb", dest: "{{ build_path }}/db/suburb_seeds.rb" }
    - { src: "{{ config_path }}/countries.yml", dest: "{{ build_path }}/db/default/spree/countries.yml" }
    - { src: "{{ config_path }}/application.yml", dest: "{{ build_path }}/config/application.yml" }
  tags: symlink

- name: symlink the bugsnag file into the config folder
  file: src="{{ config_path }}/bugsnag.rb" dest={{ build_path }}/config/bugnsag.rb state=link force=yes owner={{ user }} mode=775
  when: bugsnag_key != "none"
  tags: symlink

- name: symlink the newrelic file into the config folder
  file: src="{{ config_path }}/newrelic.yml" dest={{ build_path }}/config/newrelic.yml state=link force=yes owner={{ user }} mode=775
  when: newrelic_key != "none"
  tags: symlink

- name: symlink the s3 file to the config folder
  file: src="{{ config_path }}/s3.yml" dest={{ build_path }}/config/s3.yml state=link force=yes owner={{ user }} mode=775
  when: s3_bucket != "none"
  tags: symlink

- name: install debugger gem
  gem: name=debugger

- name: install app dependencies
  #TODO make the "--without development" part conditional on rails_env
  # Note: the 'LANG=...' is a fix for broken rubygems utf8 handling.
  command: bash -lc "bundle install --retry=3 --gemfile {{ build_path }}/Gemfile --path /home/{{ user }}/.gem --deployment" #--without development test"
  environment:
    LANG: "{{ language }}"
    LC_ALL: "{{ language }}"
    LC_COLLATE: "{{ language }}"
  register: result
  until: result.stdout.find("Connection timed out") == -1
  retries: 3
  tags: bundle_app
  notify:
    - precompile assets
    - restart unicorn

#--------------------
# Get timestamp

- name: get current date for timestamp
  shell: date +"%Y-%m-%d-%I%M%S"
  register: current_date


#--------------------------
# Create a rollback release

  # Uses sudo inline (instead of ansible format) as postgres user can't save files. @TODO need to set this up for ofn_user.
- name: create a database rollback version
  shell: sudo -u postgres pg_dump {{ db }} | gzip > {{ rollback_sql_path }}
- name: create a database backup version
  command: cp {{ rollback_sql_path }} {{ releases_path }}/{{ current_date.stdout }}.sql.gz

- name: create a repo rollback version
  command: mv {{ current_path }} {{ rollback_path }} removes={{ current_path }}
- name: create a repo backup version
  command: cp -r {{ rollback_path }} {{ releases_path }}/{{ current_date.stdout }} removes={{ rollback_path }}

#-------------------------
# Move new code into place

- name: move build to current
  command: mv {{ build_path }} {{ current_path }} removes={{ build_path }}

#--------------------
# Update the database

- name: check database status
  command: psql -U postgres -d {{ db }} -c "SELECT true FROM pg_tables WHERE tablename = 'order_cycles';"
  sudo: yes
  sudo_user: postgres
  register: table_exists
  ignore_errors: yes
  tags: rake

- name: create database if it doesnt exist
  command: bash -lc "bundle exec rake db:create RAILS_ENV={{ rails_env }}" chdir="{{ current_path }}"
  when: table_exists.stderr.find('does not exist') != -1
  tags: rake

# TODO fix this so it actually works if the database exists but the table doesn't.
- name: load schema if it isnt loaded
  command: bash -lc "bundle exec rake db:schema:load RAILS_ENV={{ rails_env }}" chdir="{{ current_path }}"
  # TODO check that both database and table do not exist so this still runs if the database is already there but empty.
  when: table_exists.stderr.find('does not exist') != -1
  tags: rake

- name: migrate database
  command: bash -lc "bundle exec rake db:migrate RAILS_ENV={{ rails_env }}" chdir="{{ current_path }}"
  tags: rake
  notify:
    - precompile assets
    - restart unicorn

- name: seed database
  # We run a shell script that passes the default email and password to rake with an EOF block, so we don't hang on the prompts.
  command: bash -lc "{{ config_path }}/seed.sh RAILS_ENV={{ rails_env }}" chdir="{{ current_path }}"
  when: table_exists.stderr.find('does not exist') != -1
  tags: rake
  notify:
    - precompile assets
    - restart unicorn

# Fix to get around database errors when this is done before schema:load. TODO fix this elsewhere.
- name: symlink spree initializer into the repo
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  with_items:
    - { src: "{{ config_path }}/spree.rb", dest: "{{ current_path }}/config/initializers/spree.rb" }
  tags:
    - rake

