---

- name: restart unicorn
  command: psql -U postgres -d {{ db }} -c "SELECT true FROM pg_tables WHERE tablename = 'order_cycles';"
  sudo: yes
  sudo_user: postgres
  register: table_exists
  ignore_errors: yes
  notify: restart unicorn step 2

#TODO make sure both of these things run as one handler.
- name: restart unicorn step 2
  # service:
  #   name: unicorn_{{ app }}
  #   state: restarted
  shell: bash -lc "service unicorn_{{ app }} restart"
  when: table_exists.stderr.find('does not exist') == -1
  # If unicorn isn't actually started yet we probably need this:
  notify: start unicorn

- name: start unicorn
  # service:
  #   name: unicorn_{{ app }}
  #   state: started
  shell: bash -lc "service unicorn_{{ app }} start"

