---
language: python
python: "2.7"

env:
  global:
    - secure: "jOc11fDH4Gjz1jnosJKlSp8RjRkD4QGHK9y04v0KVFG+1HCOWoXvMsMacRvMkkpGI0SiA98Vw7LW3ofOeuJP88Im0lAzTtXE/IvC5yQrTMmfCDSexA3ImlDl3DDjUEethRR94guKvd0bQrxKsOjh/ZLeFE8M+fGY517trl/lxfo="
    - secure: "GY+49YUvwG87/mARqkX44quecHxWNabA51umY7mFMqZWD4LU8mC0G3N90PhLzkMtv3HRt0UnnyXMdGdYWndMZ3hahBYhw5cFFk20FMhHKhL4yNXS/tYv6nT0VqsT+h2sUvLbE/RHosWswiO297Wvt9kRcSUvQ2MsPxhtsxKjDr8="

before_install:
  # Make sure everything's up to date.
  # - sudo apt-get update -qq

install:
  - pip install dopy
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\n' > ansible.cfg
  - printf 'roles_path = ../' >> ansible.cfg

  # Add extra ansible role dependencies
  - ansible-galaxy install zzet.rbenv
  - ansible-galaxy install mortik.nginx-rails

before_script:
  - cp vars.example.yml vars.yml

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/digital_ocean.yml --connection=local -e user=travis
  - ansible-playbook -i tests/inventory tests/digital_ocean_cleanup.yml --connection=local -e user=travis

  #- ansible-playbook -i tests/inventory provision.yml --connection=local -e user=travis -e pg_version=9.1 -vvvv
  #- ansible-playbook -i tests/inventory deploy.yml --connection=local -e user=travis -e pg_version=9.1 -vvvv

