---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - sudo ansible-galaxy install zzet.rbenv
  - sudo ansible-galaxy install mortik.nginx-rails

  # Add ansible.cfg to pick up roles path.
  # - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

before_script:
  - cp vars.example.yml vars.yml

script:
  # We'll add some commands to test the role here.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

