--- # Bundler - here separeately as it needs to load after the rbenv role.

- shell: ruby --version
  register: debug
- debug: var=debug

- shell: which rbenv
  register: debug
  ignore_errors: yes
- debug: var=debug

- shell: rbenv versions
  register: debug
  ignore_errors: yes
- debug: var=debug

- command: bash -lc "rbenv versions"
  register: debug
  ignore_errors: yes
- debug: var=debug

- name: install bundler
  # This needs to be run inside a bash shell to initialise rbenv, might be doable with shell command somehow...
  # See http://stackoverflow.com/questions/22115936/install-bundler-gem-using-ansible for more info.
  # Alternately rbenv could be set in environment variables somehow?
  command: bash -lc "gem install bundler  --no-ri --no-rdoc"

- name: reload rbenv
  command: bash -lc "rbenv rehash"

- setup:
  register: d_setup
  tags: setup

- debug: var=d_setup
  tags: setup

- command: which bundle
  register: d_which
  tags: dd

- debug: var=d_which
  tags: dd

- command: gem list
  register: debug
  tags: dd
- debug: var=debug
  tags: dd

- command: bash -lc "gem list"
  register: debug
  tags: dd
- debug: var=debug
  tags: dd

- command: gem env
  register: debug
  tags: dd
- debug: var=debug
  tags: dd

- command: bash -lc "gem env"
  register: debug
  tags: dd
- debug: var=debug
  tags: dd

